version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: es
    environment:
      - discovery.type=single-node
      - node.name=es
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300