version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password # 数据库root密码
      - TZ=Asia/Shanghai
    volumes:
      - ./db_data:/var/lib/mysql
      - ./tables_xxl_job.sql:/docker-entrypoint-initdb.d/init.sql # 初始化xxl-job数据
