version: "3"
services: 
  poste:
    image: "analogic/poste.io:2.3.10"
    container_name: "poste"
    restart: "always"
    volumes: 
      - "/etc/localtime:/etc/localtime:ro"
      - "poste-data:/data"
    hostname: "mail.nbtyfood.com"
    ports: 
      - "25:25"
      - "808:80"
      - "110:110"
      - "143:143"
      - "4434:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
  
volumes: 
  poste-data: