version: "3"
services: 
  poste:
    image: "analogic/poste.io:2.3.10"
    container_name: "poste"
    restart: "always"
    volumes: 
      - "/etc/localtime:/etc/localtime:ro"
      - "/poste-data:/data"
    hostname: "mail.nbtyfood.com"
    network_mode: host