version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-lab
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=password #密码
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - /mnt/iscsi/mysql/data:/var/lib/mysql
      - /mnt/iscsi/mysql/etc:/etc/mysql/conf.d
