version: '3'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sonar/postgres/postgresql:/var/lib/postgresql
      - ./sonar/postgres/data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: user #数据库用户
      POSTGRES_PASSWORD: password #数据库密码
      POSTGRES_DB: sonar

  sonarqube:
    depends_on:
      - postgres
    image: sonarqube:9.9.0-community
    container_name: sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonar/sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonar/sonarqube/logs:/opt/sonarqube/logs
      - ./sonar/sonarqube/data:/opt/sonarqube/data
      - ./sonar/sonarqube/conf:/opt/sonarqube/conf
    environment:
      SONARQUBE_JDBC_USERNAME: user #数据库用户
      SONARQUBE_JDBC_PASSWORD: password #数据库密码
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
    
    