- hosts: k8s
  vars:

  remote_user: root
  gather_facts: false
  tasks:
  - name: 关闭firewalld
    service: name=firewalld state=stopped enabled=no
  - name: 关闭selinux
    lineinfile:
      dest: /etc/selinux/config
      regexp: "^SELINUX="
      line: "SELINUX=disabled"