- hosts: k8s
  vars:
    k8s_version: 1.23.8-00
  remote_user: root
  gather_facts: false
  tasks:
  - name: 设置主机名
    shell:
      cmd: echo "127.0.0.1   $(hostname)" >> /etc/hosts
  - name: 安装网络插件
    apt:
      name: net-tools
      update_cache: yes
  - name: 关闭swap
    shell: |
      swapoff -a
      sed -ri 's/.*swap.*/#&/' /etc/fstab
  - name: 加载模块
    shell:
      cmd: modprobe br_netfilter
  - name: 新建k8s.conf文件
    shell: |
      cat <<EOF >  /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF
  - name: 修改的桥接网络设置
    shell:
      cmd: sysctl -p /etc/sysctl.d/k8s.conf
  - name: 添加国内源
    shell: |
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      cat <<EOF >/etc/apt/sources.list.d/docker.list
      deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
      EOF
  - name: 更新国内源
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: 添加k8s源
    shell: |
      curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | apt-key add -
      cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
      deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
      EOF
  - name: 安装软件
    apt:
      name: 
      - docker.io
      - kubectl=1.23.8-00
      - kubelet=1.23.8-00
      - kubeadm=1.23.8-00
      update_cache: yes
  - name: 加载软件
    shell: |
      cat > /etc/docker/daemon.json <<EOF
      {
          "exec-opts": ["native.cgroupdriver=systemd"]
      }
      EOF
      mkdir /var/lib/kubelet
      cat > /var/lib/kubelet/config.yaml <<EOF
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd
      EOF
  - name: 重载软件
    shell: ｜
      systemctl daemon-reload
      systemctl restart docker
      systemctl restart kubelet


