# 部署应用
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobcher-blog-deployment
  labels:
    app: jobcher-blog	
spec:	        
  replicas: 3
  selector:
    matchLabels:
      app: jobcher-blog
  minReadySeconds: 10 #准备10s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 #更新期间不少于3-1
      maxSurge: 1 #更新期间不超过3+1
  template:
    metadata:
      labels:
        app: jobcher-blog
    spec:
      containers:
      - name: jobcher-blog-pod
        image: hub.jobcher.com/blog/hugo:latest
---
#暴露端口
apiVersion: v1
kind: Service
metadata:
  name: jobcher-service
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: layer2
    eip.openelb.kubesphere.io/v1alpha2: layer2-eip
  labels:
    app: jobcher-blog
spec:
  selector:
    app: jobcher-blog
  ports:
  - name: jobcher-port
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer