version: '3'
services:
  dokuwiki:
    image: bitnami/dokuwiki:20220731
    container_name: dokuwiki
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './dokuwiki_data:/bitnami/dokuwiki'
    restart: always
volumes:
  dokuwiki_data:
    driver: local
