version: '3'
services:
  dokuwiki:
    image: bitnami/dokuwiki:20220731
    container_name: dokuwiki
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './dokuwiki_data:/bitnami/dokuwiki'
    restart: always
    environment:
      - DOKUWIKI_WIKI_NAME=wikijobcher
      - DOKUWIKI_FULL_NAME=jobcher
      - DOKUWIKI_EMAIL=nb@nbtyfood.com
      - DOKUWIKI_USERNAME=jobcher
      - DOKUWIKI_PASSWORD=password
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "10"
    networks:
      - dokuwiki-tier
networks:
  dokuwiki-tier:
    external: false