version: '3'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./file_sd:/etc/prometheus/file_sd
        network_mode: host

    alertmanager:  #预警模块
        image: prom/alertmanager
        container_name: alertmanager
        hostname: alertmanager
        restart: always
        network_mode: host

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        network_mode: host
    
    #snmp
    snmp-exporter:
      image: prom/snmp-exporter
      container_name: snmp-exporter
      command:
        - '--config.file=/etc/snmp_exporter/snmp.yml'
      network_mode: host
      restart: always
      volumes:
      - './snmp_exporter/:/etc/snmp_exporter/'