apiVersion: v1
kind: PersistentVolume
metadata:
  name:  rockermq-pv
  namespace: sanjiang
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rocketmq-nfs-storage
  nfs:
    path: /data/storage/k8s/rocketmq
    server: 193.0.40.171