apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc2
  namespace: sanjiang
  annotations:
    volume.beta.kubernetes.io/storage-class: "rocketmq-nfs-storage"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi