version: '3'
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    volumes:
      - $PWD:/root
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    network_mode: host
    command: hbbs
  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    volumes:
      - $PWD:/root
    ports:
      - 21117:21117
    network_mode: host
    command: hbbr

