- hosts: k8s
  vars:
    k8s_version: 1.23.8-00
  remote_user: root
  gather_facts: false
  tasks:
  - name: 设置主机名
    shell:
      cmd: echo "127.0.0.1   $(hostname)" >> /etc/hosts
    tags:
      - sethosts
  - name: 安装网络插件
    apt:
      name: net-tools
      update_cache: yes
    tags:
      - installnet
  - name: 关闭swap
    shell: |
      swapoff -a
      sed -ri 's/.*swap.*/#&/' /etc/fstab
    tags:
      - swapoff
  - name: 加载模块
    shell:
      cmd: modprobe br_netfilter
    tags:
      - loadbr
  - name: 新建k8s.conf文件
    shell: |
      cat <<EOF >  /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF
    tags:
      - createk8sconf
  - name: 修改的桥接网络设置
    shell:
      cmd: sysctl -p /etc/sysctl.d/k8s.conf
    tags:
      - connnet
  - name: 添加国内源
    shell: |
      curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | apt-key add -
      cat <<EOF >/etc/apt/sources.list.d/docker.list
      deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable
      EOF
    tags:
      - addccp
  - name: 更新国内源
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: 添加k8s源
    shell: |
      curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | apt-key add -
      cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
      deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
      EOF
    tags:
      - addk8sccp
  - name: 安装软件
    apt:
      name: 
      - docker-ce
      - kubectl={{k8s_version}}
      - kubelet={{k8s_version}}
      - kubeadm={{k8s_version}}
      update_cache: yes
    tags:
      - installk8s
  - name: 加载软件
    shell: |
      cat > /etc/docker/daemon.json <<EOF
      {
          "exec-opts": ["native.cgroupdriver=systemd"]
      }
      EOF
      mkdir /var/lib/kubelet
      cat > /var/lib/kubelet/config.yaml <<EOF
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd
      EOF
    tags:
      - loadk8s
  - name: 重载docker
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker.service
    tags:
      - restartdocker
  - name: 重载k8s
    systemd:
      state: restarted
      daemon_reload: yes
      name: kubelet.service
    tags:
      - restartkubelet



