apiVersion: v1
kind: ConfigMap
metadata:
  name: skywalking-config
  namespace: dev-center
data:
  application.yml: |
    skywalking:
      oap:
        server:
          grpc:
            port: 11800
          http:
            port: 12800
      storage:
        type: elasticsearch
        elasticsearch:
          cluster: elasticsearch
          port: 9200
          timeout: 3000
          # username: "elastic"            # 如果使用了用户认证
          # password: "YOUR_PASSWORD"      # 密码，如果没有设置则可省略