apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: dev-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        env:
        - name: discovery.type
          value: single-node  # 单节点部署
        - name: ES_JAVA_OPTS
          value: "-Xmx1g -Xms1g"  # 配置内存
        - name: xpack.security.enabled
          value: "false"  # 关闭安全认证
        - name: cluster.name
          value: elasticsearch  # 集群名称
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data  # 挂载到容器内的数据目录
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-pvc  # PVC 引用
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: dev-center
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
